library verilog;
use verilog.vl_types.all;
entity oci_sys is
    generic(
        UI_IRCODE       : integer := 48;
        UI_DRCODE       : integer := 49;
        IRC_JTAG        : integer := 0;
        IRC_JTAG1       : integer := 1;
        IRC_TRACECMD    : integer := 2;
        IRC_DEBUGCMD    : integer := 3;
        IRC_CMD         : integer := 4;
        IRC_TRIGGER     : integer := 5;
        IRC_TRACE       : integer := 6;
        IRC_BYPASS      : integer := 7;
        IR_EXTEST       : integer := 0;
        IR_SAMPLE       : integer := 1;
        IR_IDCODE       : integer := 2;
        IR_TraceAddr    : integer := 64;
        IR_TraceStop    : integer := 68;
        IR_TraceStart   : integer := 69;
        IR_TraceClear   : integer := 70;
        IR_DebugNop     : integer := 96;
        IR_ResetCPU     : integer := 121;
        IR_DebugReqOff  : integer := 104;
        IR_DebugReqOn   : integer := 105;
        IR_DebugStepUser: integer := 109;
        IR_DebugStepOCI : integer := 107;
        IR_DebugPswrOn  : integer := 129;
        IR_DebugPswrOff : integer := 128;
        IR_AuxOn        : integer := 134;
        IR_AuxOff       : integer := 132;
        IR_Trigger      : integer := 160;
        IR_GetPC        : integer := 208;
        IR_TraceData    : integer := 216;
        IR_BYPASS       : integer := 255;
        TRIGMODE_PROGRD : integer := 0;
        TRIGMODE_PROGWR : integer := 1;
        TRIGMODE_XDATARD: integer := 2;
        TRIGMODE_XDATAWR: integer := 3;
        TRIGMODE_IDATARD: integer := 4;
        TRIGMODE_IDATAWR: integer := 5;
        TRIGMODE_SFRRD  : integer := 6;
        TRIGMODE_SFRWR  : integer := 7;
        IDCODE_A8051    : integer := 96;
        IDCODE_A8051_UJTAG: integer := 104;
        BKPT            : integer := 165;
        DEBUG           : integer := 1;
        INCL_TRACE      : integer := 1;
        TRIG_NUM        : integer := 0;
        EN_FF_OPTS      : integer := 0;
        APB_DWIDTH      : integer := 32;
        INCL_DPTR1      : integer := 1;
        INCL_MUL_DIV_DA : integer := 1;
        VARIABLE_STRETCH: integer := 1;
        STRETCH_VAL     : integer := 1;
        VARIABLE_WAIT   : integer := 1;
        WAIT_VAL        : integer := 0;
        INTRAM_IMPLEMENTATION: integer := 0;
        WAITSTATES      : integer := 0
    );
    port(
        clk             : in     vl_logic;
        resetiB         : in     vl_logic;
        tck             : in     vl_logic;
        tdi             : in     vl_logic;
        tms             : in     vl_logic;
        tdo             : out    vl_logic;
        TRSTB           : in     vl_logic;
        TrigOut         : out    vl_logic;
        BreakIn         : in     vl_logic;
        BreakOut        : out    vl_logic;
        AuxOut          : out    vl_logic
    );
end oci_sys;
