<project name="led_test" version="1.1">
    <ProjectDirectory>
        C:\Users\zackp\OneDrive\Documents\ECE_4806\Libero\ethernet_module\designer\impl1\led_test_fp
    </ProjectDirectory>
    <View>
        SingleSTAPLView
    </View>
    <LiberoTargetDevice>
        
    </LiberoTargetDevice>
    <LogFile>
        C:\Users\zackp\OneDrive\Documents\ECE_4806\Libero\ethernet_module\designer\impl1\led_test_fp\led_test.log
    </LogFile>
    <SerializationOption>
        Skip
    </SerializationOption>
    <programmer status="enable" type="FlashPro4" revision="UndefRev" connection="usb2.0">
        <name>
            05191
        </name>
        <id>
            05191
        </id>
    </programmer>
    <configuration>
        <Hardware>
            <FlashPro>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
                <Vddl/>
                <Vdd>
2500                </Vdd>
            </FlashPro>
            <FlashProLite>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
            </FlashProLite>
            <FlashPro3>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro3>
            <FlashPro4>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro4>
            <FlashPro5>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
                <ProgrammingMode>
                    JTAGMode
                </ProgrammingMode>
            </FlashPro5>
        </Hardware>
        <Algo type="PDB">
            <filename>
                C:\Users\zackp\OneDrive\Documents\ECE_4806\Libero\ethernet_module\designer\impl1\ethernet_module.pdb
            </filename>
            <local>
                projectData\ethernet_module.pdb
            </local>
            <SelectedAction>
                PROGRAM
            </SelectedAction>
        </Algo>
    </configuration>
</project>
